### ISSUE TITLE
About the input of Attention Gate

### ISSUE THREAD

**Issue by lHou157** [LeeJunHyun/Image_Segmentation#14]
Thanks for your sharing! But there is a question that I think  g=d5 should be written as g=x5 as shown in the following figure. I don't know whether the way I understand is right or not. If not, please point out!
![1554994303(1)](https://user-images.githubusercontent.com/32443777/55967281-9ecee400-5cac-11e9-8c27-bdce0b2e8c88.jpg)
![1554994628(1)](https://user-images.githubusercontent.com/32443777/55967607-2ddbfc00-5cad-11e9-9ba0-c88e6975026f.jpg)

**Comment by LeeJunHyun** [comment]
Hi, @lHou157 .
 
Because the spatial size (resolution) of `x5` is different with `x4`, `x5` should be upsampled to be used as gating signal.
In the attention gate block, the gating signal `g` and the input signal `x` are summed after 1x1 conv.
So I used `d5` as gating signal.
But if you have better idea, this can be implemented with a nice way.

Thank you :)

**Comment by lHou157** [comment]
Thank you！ I have caught your meanings. You are really a nice one!

**Comment by LeeJunHyun** [comment]
Thank you! If you have more issues, plz leave a comment whenever :)

**Comment by sudohainguyen** [comment]
Hi @LeeJunHyun , In the original paper, it is written that x is down-sampled within the attention module as described in this pic instead of upsampling the gate as you have been doing. How do you think?

![](https://ars.els-cdn.com/content/image/1-s2.0-S1361841518306133-gr2.jpg)
