### ISSUE TITLE
If I input size is 512x512?

### ISSUE THREAD

**Issue by zhaoxuyan** [LeeJunHyun/Image_Segmentation#19]
I download the ISIC 2018 training dataset, and the size of images is `4288x2848`
but in your code the `image_size=224`. Why?
If my original custom data's size is `512x512`, should I resize it to ` 224x224`?

How could I change the `data_loader.py`? I think I should change the following lines:
```python
# image_size=224
ResizeRange = random.randint(300,320)
CropRange = random.randint(250,270)
Transform.append(T.Resize((int(256*aspect_ratio)-int(256*aspect_ratio)%16,256)))
```
And should I also change the model architecture in the `network.py` after I change the input size?

Thanks in advance!!!

**Comment by LeeJunHyun** [comment]
Hi, @zhaoxuyan , 
I manually set the parameter of resize (or crop range) in `data_loader.py`, but you can fix them properly if your image have different size. 
I will clean up my codes ASAP :(
plz ignore the code `image_size=224` in preprocessing.

And you don't have to change the code of `network.py`, because it is fully convolutional network.

Thank you for your interest and issue :)

**Comment by zhaoxuyan** [comment]
Thanks for your reply!

**Comment by micklexqg** [comment]
is a odd inputsize such as 317x423 ok?
