### ISSUE TITLE
Attention gate after upsampling

### ISSUE THREAD

**Issue by Glaadiss** [LeeJunHyun/Image_Segmentation#74]
Hey, in this paper https://arxiv.org/pdf/1804.03999.pdf and other tutorials the attention gate takes the gating signal from the same block that is being unsampled in the next step, whereas in the code in this repo the gating signal comes from the block, which is already unsampled. Is this correct and I'm missing something, or this is a mistake?

how it is now:
```python
  # AttU_net in forward func
  d5 = self.Up5(x5)
  x4 = self.Att5(g=d5,x=x4)
  d5 = torch.cat((x4,d5),dim=1)        
  d5 = self.Up_conv5(d5)
```

how it should be based on the paper:
```python
  # AttU_net in forward func
  x4 = self.Att5(g=d5,x=x4)
  d5 = self.Up5(x5)
  d5 = torch.cat((x4,d5),dim=1)        
  d5 = self.Up_conv5(d5)
```

**Comment by Lloyd-Pottiger** [comment]
According to the offical code of the paper: https://github.com/ozan-oktay/Attention-Gated-Networks
the gating signal is mainly:
```
nn.Sequential(nn.Conv3d(in_size, out_size, kernel_size, (1,1,1), (0,0,0)),
      nn.BatchNorm3d(out_size),
      nn.ReLU(inplace=True),
)
```
And then input into Attention Gate, in order to match the size of encoding layer, we need to do upsampling of the output of gating signal. Therefore, this version just minus the one conv which called gating sigal. I think it is not necessary but can reduce a lot of calculations. I will make a compare when I am free.

**Comment by Ankan1998** [comment]
Yes, I was also going through the attention Unet code, they are not in coherence with paper
<img width="786" alt="unetattn" src="https://user-images.githubusercontent.com/36896102/143673322-a40154f3-a45e-44b0-90e4-f6149f54a779.PNG">

The gating signal channel dimension should be double of skipping and the feature map should be halved. But here It is implemented in a different way

**Comment by HulahaVla** [comment]
yeah, an ye yi yang
